### ISSUE TITLE
recipe branch

### ISSUE THREAD

**Issue by jkuzhila** [jjyoo03/RecipeApp_SoftDeve_Group1#1]
There isn’t anything to compare.
main and recipe are entirely different commit histories.

**Comment by mr-mohit** [comment]
Your branch does not have a lot changes that are already in main branch and merging it will lead to breaking the code on main which is already running. Therefore, can you please clone the main branch and then copy the changes that you did in the your branch to that cloned branch and make sure it is running without errors before opening pull request.

**Comment by mr-mohit** [comment]
Your branch does not have a lot changes that are already in main branch and merging it will lead to breaking the code on main which is already running. Therefore, can you please clone the main branch and then copy the changes that you did in the your branch to that cloned branch and make sure it is running without errors before opening pull request.
